---
title: "Eviction Rate Regression Model"
tags: ["R", "regression"]
weight: 1
draft: false
output: html_document
---

### Main Findings 

This research uses data from The Eviction Lab at Princeton University, a project directed by Matthew Desmond and designed by Ashley Gromis, Lavar Edmonds, James Hendrickson, Katie Krywokulski, Lillian Leung, and Adam Porton. The Eviction Lab is funded by the JPB, Gates, and Ford Foundations as well as the Chan Zuckerberg Initiative. More information is found at evictionlab.org. For our primary data source, we used the Eviction Lab’s records on evictions at the 2010 census tract level for all cities.

We also used tract level data from the 2013-2017 American Community Survey on highest educational attainment and unemployment, and state level policy variables related to protections for landlords and tenants. As we wanted to analyze the model’s results for Richmond, VA, we also utilized the Missouri Census Data Center's 2018 Geocorr database to understand tracts in terms of their corresponding census places, namely cities.

In our regression model, we analyzed tracts whose parent cities had a population between 100,000-300,000. We narrowed the variables list to the most well supported and developed an initial model to determine factors that were not significant or were highly correlated with other variables. These variables, in addition to variables with high variance inflation factors, were dropped. The response variable evictionrate underwent a square root transformation to address heteroscedasticity.  
In the final model, all variables were significant at the 0.05 significance level. The reference level was the percentage of the total population estimated in the 2011-2016 ACS identifying racially as white, Native Hawaiian and Other Pacific Islander, American Indian and Alaska Native, two or more races, or as Other race.

Compared to this population, estimates of a unit increase in the following variables were associated with increases in the squared root eviction rate: 

* The number of protected class exemptions in housing-related transactions in state law and 0.3935, 
* Whether tenants in the state are protected from retaliation by landlords after asserting their legal rights and 0.2037, 
* Number of exemptions landlords have from state landlord-tenant law and 0.1267, percentage of tract that is Black or African American and not Hispanic or Latino (2011-2016 ACS) and 0.01006, 
* Percentage of tract aged 16+ who are unemployed and 0.0215, and tract poverty rate and 0.0046.

A unit increase in the following variables were associated with decreases in the squared root eviction rate: 

* The number of total legal remedies available to tenants in state law and -0.8689, * The number of total legal remedies available to landlords in state law and -0.4012, 
* Percentage of tract aged 25+ with a bachelor’s degree or higher and -0.0106, 
* Percentage of tract that is Asian and -0.0019, percentage of tract that is Hispanic and -0.0011. 

The model’s adjusted R-squared was 0.6904, with an F-statistic of 70.84 on 83 and 2516 degree of freedom, with a residual standard error of 0.4703. 

### Conclusion and Policy Implications 

We determined that policy changes were the most important type of factor in understanding eviction rates, while most demographic factors may play a more limited role. The factor most highly associated with increased eviction rates was the number of protected class exemptions in the state, while the factor most highly associated with decreased eviction rates was total legal remedies available to tenants in the state. 

These results provide evidence that state tenant-landlord law, and potentially other policy impacting this relationship and its associated transactions, is important in explaining eviction rates. The evidence of relationships provided in this analysis should inform future decision making in eviction and housing policymaking. Particularly for policy makers intending to reduce eviction rates, the following recommendations may be prudent for future study:

* Reduce number of protected class exemptions in housing-related transactions in state law
* Protect tenants from retaliation by landlords
* Reduce the number of exemptions landlords have from state landlord-tenant law 
* Increase the number of total legal remedies available to tenants and landlords in state law

### References 

Eviction Lab Data Downloads. (2018). Retrieved July 30, 2020, from https://eviction-lab-data-downloads.s3.amazonaws.com/DATA_DICTIONARY.txt

Missouri Census Data Center. (2018). Retrieved July 30, 2020, from http://mcdc.missouri.edu/applications/geocorr2018.html
