---
title: "References"
weight: 4
draft: false
output: html_document
---
<!-- ###References {style=text-align:center} -->

Eviction Lab Data Downloads. (2018). Retrieved July 30, 2020, from https://eviction-lab-data-downloads.s3.amazonaws.com/DATA_DICTIONARY.txt

Missouri Census Data Center. (2018). Retrieved July 30, 2020, from http://mcdc.missouri.edu/applications/geocorr2018.html

Eviction Lab Data: Matthew Desmond, Ashley Gromis, Lavar Edmonds, James Hendrickson, Katie Krywokulski, Lillian Leung, and Adam Porton. Eviction Lab National Database: Version 1.0. Princeton: Princeton University, 2018, www.evictionlab.org. 

Washington, Lark. "Rehouse Richmond: Plan to Address the Eviction Crisis." (2020). 
Desmond, Matthew. "Eviction and the reproduction of urban poverty." American Journal of Sociology 118.1 (2012): 88-133. 

Teresa, B. "The Geography of Eviction in Richmond: Beyond Poverty." RVA Eviction Lab. Geographies of Eviction. pdf (2018). 

Lempert, Richard, and Kiyoshi Ikeda. "Evictions from public housing: effects of independent review." American Sociological Review (1970): 852-860. 
