### 2020 Richmond City Summer Project {style=text-align:center}
### Data and Methodology {style=text-align:center}

This research uses data from The Eviction Lab at Princeton University, a project directed by Matthew Desmond and designed by Ashley Gromis, Lavar Edmonds, James Hendrickson, Katie Krywokulski, Lillian Leung, and Adam Porton. The Eviction Lab is funded by the JPB, Gates, and Ford Foundations as well as the Chan Zuckerberg Initiative. More information is found at evictionlab.org. For our primary data source, we used the Eviction Lab’s records on evictions at the 2010 census tract level for all cities.

We also used tract level data from the 2013-2017 American Community Survey on highest educational attainment and unemployment, and state level policy variables related to protections for landlords and tenants. As we wanted to analyze the model’s results for Richmond, VA, we also utilized the Missouri Census Data Center's 2018 Geocorr database to understand tracts in terms of their corresponding census places, namely cities.

In our regression model, we analyzed tracts whose parent cities had a population between 100,000-300,000. We narrowed the variables list to the most well supported through a literature search and developed an initial model to determine factors that were not significant or were highly correlated with other variables. 

These variables, in addition to variables with high variance inflation factors or other variables with high collinearity by correlation matrix, were dropped. This procedure dropped medianhouseholdincome, which had the highest VIF. The response variable evictionrate underwent a square root transformation to address heteroscedasticity.

Our final model: 
#\begin{eqnarray}
$$
\begin{split}
\sqrt{evictionrate} = 2.180568248 + \\
0.004637722 \cdot povertyrate +     \\   
0.021455878 \cdot \text{perc 16yrs and over unemployed} +  \\
-0.010635330 \cdot \text{perbachandup} + \\
 0.010059336 \cdot \text{pctafam} + \\
 -0.001889045 \cdot \text{pctasian} + \\
 -0.001125114  \cdot \text{pcthispanic} + \\
 0.126704748 \cdot  \text{SLT EXEMPT TOTAL} + \\
 -0.868900102 \cdot \text{SLT TREMEDIES TOTAL} + \\
 0.203698303 \cdot \text{SLT Retaliation} + \\
 0.393518820 \cdot \text{FHP ExemptHousing TOTAL} + \\
 -0.401157873 \cdot \text{SLT LREMEDIES_TOTAL} + \\
 \dots + -0.38142290 \cdot \text{cityRichmond city, VA}  \\
 \end{split} $$
#\end{eqnarray}

In the final model, all variables were significant at the 0.05 significance level. The reference level was the percentage of the total population estimated in the 2011-2016 ACS identifying racially as white, Native Hawaiian and Other Pacific Islander, American Indian and Alaska Native, two or more races, or as Other race.
